server:
  port: 8081
spring:
  application:
    name: jpa-data-mapping
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/jpa_mapping
    username: techguy
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://127.0.0.1:9411/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true


